export const REQUEST_USER = Symbol("User")
export const REQUEST_TARGET_USER = Symbol("TargetedUser")
export const REQUEST_TARGET_USER_ID = Symbol("TargetedUserId")
export const REQUEST_TOKEN = Symbol("Token")
export const REQUEST_TOKEN_ID = Symbol("TokenID")
export const REQUEST_VERIFIED_JWT = Symbol("Token")
export const REQUEST_EMAIL = Symbol("Email")
export const REQUEST_DB = Symbol("DatabaseInstance")
