name: Bump Version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Bump Version
        id: bump_version
        run: |
          npm version patch
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git push origin HEAD:main --follow-tags

      - name: Push Changes
        if: success()
        run: |
          git add package.json
          git commit -m "ci: bump version to ${{ steps.bump_version.outputs.new_version }}"
          git push origin main
