name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  initialise:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

  install:

    - name: Install dependencies
      run: npm install

  test:

    - name: Run tests
      run: npm test

  build:

    - name: Run build
      run: npm run build

  report:

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Run Typescript coverage report
      run: npm run typecoverage
